[advisories]
ignore = [
  # Unmaintained crates that fvm2 requires, and will not change for
  # compatability/consensus reasons - see
  # https://github.com/filecoin-project/ref-fvm/issues/1843
  "RUSTSEC-2022-0061", # parity-wasm is deprecated
  "RUSTSEC-2024-0436", # paste is unmaintained
  "RUSTSEC-2025-0141", # bincode is unmaintained
]

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "ISC",
  "MIT",
  "OpenSSL",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]

exceptions = [
  { allow = [
    "CDLA-Permissive-2.0",
  ], crate = "webpki-roots" },
  { allow = [
    "CDLA-Permissive-2.0",
  ], crate = "webpki-root-certs" },
  { allow = [
    "MPL-2.0",
  ], crate = "option-ext" },
  { allow = [
    "MPL-2.0",
  ], crate = "colored" },
  { allow = [
    "MPL-2.0",
  ], crate = "cbindgen" },
  { allow = [
    "MPL-2.0",
  ], crate = "attohttpc" },
]

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "allow"
