[package]
name = "commcid"
description = "Filecoin commitment to Cid conversion utilities"
version = "0.1.1"
license = "MIT OR Apache-2.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"
repository = "https://github.com/ChainSafe/forest"

[dependencies]
cid = { package = "forest_cid", version = "0.3" }

[dev-dependencies]
rand = "0.7.3"
