[package]
name = "forest_address"
description = "Filecoin addresses for use in Forest"
license = "MIT OR Apache-2.0"
version = "0.3.1"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"
repository = "https://github.com/ChainSafe/forest"

[dependencies]
num-traits = "0.2"
num-derive = "0.3.0"
data-encoding = "2.1.2"
data-encoding-macro = "0.1.7"
leb128 = "0.2.1"
encoding = { package = "forest_encoding", version = "0.2.1" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
forest_json_utils = { version = "0.1", optional = true }
once_cell = "1.7.2"

[features]
json = ["forest_json_utils"]
testnet = []