[package]
name = "forest_state_migration"
license.workspace = true
repository.workspace = true
version.workspace = true
authors.workspace = true
edition = "2021"

[dependencies]
ahash.workspace = true
anyhow.workspace = true
cid.workspace = true
crossbeam-channel = "0.5"
filecoin-proofs-api.workspace = true
forest_networks.workspace = true
forest_shim.workspace = true
forest_utils.workspace = true
frc46_token = "3.1"
fvm_ipld_blockstore.workspace = true
fvm_ipld_encoding.workspace = true
fvm_ipld_hamt.workspace = true
fvm_shared.workspace = true
lazy_static.workspace = true
log.workspace = true
num_cpus.workspace = true
rayon.workspace = true
unsigned-varint.workspace = true

fil_actor_datacap_state.workspace = true
fil_actor_init_state.workspace = true
fil_actor_interface.workspace = true
fil_actor_market_state.workspace = true
fil_actor_miner_state.workspace = true
fil_actor_power_state.workspace = true
fil_actor_system_state.workspace = true
fil_actor_verifreg_state.workspace = true
fil_actors_shared.workspace = true
