[package]
name = "graphsync"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"

[dependencies]
protobuf = "2.14.0"
cid = { package = "forest_cid", version = "0.3" }
forest_ipld = "0.1.1"
fnv = "1.0.6"
encoding = { package = "forest_encoding", version = "0.2.1" }
libp2p = { version = "0.35", default-features = false }
futures = "0.3.5"
futures-util = "0.3.5"
futures_codec = "0.4.0"
log = "0.4.8"
bytes = "1.0"
unsigned-varint = { version = "0.6", features = ["futures-codec"] }
smallvec = "1.1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
ipld_blockstore = "0.1"

[build-dependencies]
protoc-rust = "2.14.0"

[dev-dependencies]
multihash = { version = "0.13", default-features = false, features = ["std", "blake2b", "derive"] }
async-std = "1.9"
rand = "0.7"