[package]
name = "net_utils"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"

[dependencies]
isahc = "0.9.11"
url = "2.1.1"
log = "0.4.8"
thiserror = "1.0"
pbr = "1.0.3"
pin-project-lite = "0.2"
async-std = { version = "1.9", features = ["attributes"] }
futures = "0.3.5"