[package]
name = "forest_car"
version = "0.1.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"

[dependencies]
cid = { package = "forest_cid", version = "0.3", features = ["cbor"] }
forest_encoding = "0.2.1"
blockstore = { package = "ipld_blockstore", version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
futures = "0.3.5"
integer-encoding = { version = "3.0", features = ["futures_async"] }

[dev-dependencies]
db = { package = "forest_db", version = "0.1" }
async-std = { version = "1.9", features = ["attributes"] }
