[package]
name = "forest_runtime"
description = "Runtime for use in Filecoin protocol"
version = "0.2.0"
license = "MIT OR Apache-2.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"
repository = "https://github.com/ChainSafe/forest"

[dependencies]
vm = { package = "forest_vm", version = "0.3" }
crypto = { package = "forest_crypto", version = "0.5", features = ["blst"] }
address = { package = "forest_address", version = "0.3" }
cid = { package = "forest_cid", version = "0.3" }
ipld_blockstore = "0.1"
clock = { package = "fil_clock", path = "../../node/clock", version = "0.1" }
forest_encoding = "0.2.1"
commcid = { path = "../../utils/commcid", version = "0.1.1" }
filecoin-proofs-api = { version = "9", features = ["blst"], default_features = false }
base64 = "0.13"
fil_types = { features = ["proofs"], version = "0.2" }
log = "0.4.8"

[dev-dependencies]
interpreter = { path = "../interpreter/" }
db = { package = "forest_db", version = "0.1" }
