# This workflows, run daily, updates the Forest CLI usage docs, and submits a PR with the changes.
name: Update Forest usage docs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-docs:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - name: Run update script
        run: |
          cd docs/docs/users/reference
          ./generate_cli_md.sh docker > cli.md
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          package-manager-cache: false
      - run: corepack enable
      - run: pnpm i --frozen-lockfile
      - run: pnpm md-fmt
      # This is needed in order to have the commits signed.
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.LESHY_APP_ID }}
          private-key: ${{ secrets.LESHY_APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          base: main
          branch: leshy/update-forest-docs
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update Forest CLI docs
          sign-commits: true
          title: "[automated] Update Forest CLI docs"
          body: |
            ### Changes
            - Updates Forest CLI docs to the latest commit in the `main` branch.
