name: Go code linters
permissions:
  contents: read

# Cancel workflow if there is a new change to the branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/go-lint.yml"
      - "go.work"
      - "mise.toml"
      - "f3-sidecar/**"
      - "interop-tests/src/tests/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/go-lint.yml"
      - "go.work"
      - "mise.toml"
      - "f3-sidecar/**"
      - "interop-tests/src/tests/**"

jobs:
  lint-go:
    name: Go lint checks
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: mise lint:golang
