name: RPC parity tests
on:
  workflow_dispatch:
    inputs:
      image:
        description: "Forest Docker image to test against"
        required: false
        default: "ghcr.io/chainsafe/forest:edge-fat"
  schedule:
    - cron: "0 0 * * *"
jobs:
  rpc-parity:
    name: RPC parity tests
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - name: Relocate docker volumes folder
        run: |
          # move docker volumes folder to under `/mnt` which has 60GB+ free space
          sudo ls /var/lib/docker/volumes
          sudo mv /var/lib/docker/volumes /mnt/docker-volumes
          sudo ln -sf /mnt/docker-volumes /var/lib/docker/volumes
          sudo ls /var/lib/docker/volumes
          df -h
      - uses: actions/checkout@v6
      - name: Run api compare tests on calibnet
        shell: bash
        run: |
          IMAGE=${{ github.event.inputs.image }}
          if [ -z "$IMAGE" ]; then
            IMAGE="ghcr.io/chainsafe/forest:edge-fat"
          fi
          echo "FROM $IMAGE" > Dockerfile-RPC
          export FOREST_DOCKERFILE_OVERRIDE=Dockerfile-RPC
          ./scripts/tests/api_compare/setup.sh
        timeout-minutes: 30
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
      - name: Dump Docker usage
        if: always()
        run: |
          sudo ls /var/lib/docker/volumes
          docker system df
          docker system df --verbose
          df -h
      - name: Set WORKFLOW_URL
        if: always()
        run: |
          export WORKFLOW_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          echo ${WORKFLOW_URL}
          echo "WORKFLOW_URL=${WORKFLOW_URL}" >> $GITHUB_ENV
      - uses: JasonEtco/create-an-issue@v2
        if: github.ref == 'refs/heads/main' && failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/RPC_PARITY_ISSUE_TEMPLATE.md
